name: manga_volume_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  moor: ^3.0.2
  moor_ffi: ^0.5.0
  path_provider: ^1.6.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.0.0
  build_runner: ^1.9.0

flutter:
  uses-material-design: true

