name: manga_volume_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^1.1.1
  sqlite3_flutter_libs: ^0.5.2
  path_provider: ^2.0.1
  path: ^1.8.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.1.1
  build_runner: ^2.0.3

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#00687A"
  android_gravity: center
  image: assets/logo_splash.png
