name: manga_volume_tracker
description: A new Flutter project.

version: 2.0.1+1000003

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.2
  path_provider: ^2.0.1
  path: ^1.8.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.16.0
  build_runner: ^2.0.3

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#00687A"
  android_gravity: center
  image: assets/logo_splash.png
