name: manga_volume_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.3.0 
  path_provider: ^1.6.27
  path: ^1.7.0 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.4.1
  build_runner: ^1.11.0

flutter:
  uses-material-design: true

